version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5923:3000"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:16-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: book-database
    ports:
      - "5924:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: